irregulars = [sum, es, est, sumus, estis, sunt, eram, eras, erat, eramus, 
eratis, erant, ero, eris, erit, erimus, eritis, erunt, fui, fuisti, fuit,
fuimus, fuistis, fuerunt, fueram, fueras, fuerat, fueramus, fueratis, 
fuerant, perfect, fuero, fueris, fuerit, fuerimus, fueritis, fuerint, 
sim, sis, sit, simus, sitis, sint, essem, esses, esset, essemus, essetis, 
essent, fuerim, fueris, fuerit, fuerimus, fueritis, fuerint, fuissem, 
fuisses, fuisset, fuissemus, fuissetis, fuissent, es, este, esto, esto, 
estote, sunto, possum, potes, potest, possumus, potestis, possunt, 
poteram, poteras, poterat, poteramus, poteratis, poterant, potero, 
poteris, poterit, poterimus, poteritis, poterunt, potui, potuisti, 
potuit, potuimus, potuistis, potuerunt, potueram, potueras, potuerat, 
potueramus, potueratis, potuerant, perfect, potuero, potueris, potuerit, 
potuerimus, potueritis, potuerint, possim, possis, possit, possimus, 
possitis, possint, possem, posses, posset, possemus, possetis, possent, 
potuerim, potueris, potuerit, potuerimus, potueritis, potuerint, 
potuissem, potuisses, potuisset, potuissemus, potuissetis, potuissent, 
potes, poteste, potesto, potesto, potestote, possunto, eo, is, it, imus, 
itis, eunt, ibam, ibas, ibat, ibamus, ibatis, ibant, ibo, ibis, ibit, 
ibimus, ibitis, ibunt, ivi, ivisti, ivit, ivimus, ivistis, iverunt, iveram, 
iveras, iverat, iveramus, iveratis, iverant, perfect, ivero, iveris, iverit, 
iverimus, iveritis, iverint, eam, eas, eat, eamus, eatis, eant, irem, ires, 
iret, iremus, iretis, irent, iverim, iveris, iverit, iverimus, iveritis, 
iverint, ivissem, ivisses, ivisset, ivissemus, ivissetis, ivissent, i, ite, 
ito, ito, itote, eunto, volo, vis, vult, volumus, vultis, volunt, volebam, 
volebas, volebat, volebamus, volebatis, volebant, volam, voles, volet, volemus, 
voletis, volent, volui, voluisti, voluit, voluimus, voluistis, voluerunt, 
volueram, volueras, voluerat, volueramus, volueratis, voluerant, perfect, 
voluero, volueris, voluerit, voluerimus, volueritis, voluerint, velim, velis, 
velit, velimus, velitis, velint, vellem, velles, vellet, vellemus, velletis, 
vellent, voluerim, volueris, voluerit, voluerimus, volueritis, voluerint, 
voluissem, voluisses, voluisset, voluissemus, voluissetis, voluissent, nolo, 
non, vis, non, vult, nolumus, non, vultis, nolunt, nolebam, nolebas, nolebat, 
nolebamus, nolebatis, nolebant, nolam, noles, nolet, nolemus, noletis, nolent,
nolui, noluisti, noluit, noluimus, noluistis, noluerunt, nolueram, nolueras,
noluerat, nolueramus, nolueratis, noluerant, perfect, noluero, nolueris, 
noluerit, noluerimus, nolueritis, noluerint, nolim, nolis, nolit, nolimus, 
nolitis, nolint, nollem, nolles, nollet, nollemus, nolletis, nollent, noluerim, 
nolueris, noluerit, noluerimus, nolueritis, noluerint, noluissem, noluisses,
noluisset, noluissemus, noluissetis, noluissent, noli, nolite, nolito, 
nolito, nolitote, nolunto, malo, mavis, mavult, malumus, mavultis, malunt, 
malebam, malebas, malebat, malebamus, malebatis, malebant, malam, males, malet, 
malemus, maletis, malent, malui, maluisti, maluit, maluimus, maluistis, 
maluerunt, malueram, malueras, maluerat, malueramus, malueratis, maluerant, 
perfect, maluero, malueris, maluerit, maluerimus, malueritis, maluerint, malim, 
malis, malit, malimus, malitis, malint, mallem, malles, mallet, mallemus, 
malletis, mallent, maluerim, malueris, maluerit, maluerimus, malueritis, 
maluerint, maluissem, maluisses, maluisset, maluissemus, maluissetis, 
maluissent, fero, fers, fert, ferimus, fertis, ferunt, ferebam, ferebas, 
ferebat, ferebamus, ferebatis, ferebant, feram, feres, feret, feremus, feretis, 
ferent, tuli, tulisti, tulit, tulimus, tulistis, tulerunt, tuleram, tuleras, 
tulerat, tuleramus, tuleratis, tulerant, perfect, tulero, tuleris, tulerit, 
tulerimus, tuleritis, tulerint, feram, feras, ferat, feramus, feratis, ferant, 
ferrem, ferres, ferret, ferremus, ferretis, ferrent, tulerim, tuleris, 
tulerit, tulerimus, tuleritis, tulerint, tulissem, tulisses, tulisset, 
tulissemus, tulissetis, tulissent, fer, ferte, ferto, ferto, fertote, ferunto, 
feror, ferris, fertur, ferimur, ferimini, feruntur, ferebar, ferebaris, 
ferebatur, ferebamur, ferebamini, ferebantur, ferar, fereris, feretur, feremur, 
feremini, ferentur, ferar, feraris, feratur, feramur, feramini, ferantur, 
ferrer, ferreris, ferretur, ferremur, ferremini, ferrentur, fio, fis, fit, 
fimus, fitis, fiunt, fiebam, fiebas, fiebat, fiebamus, fiebatis, fiebant, fiam, 
fies, fiet, fiemus, fietis, fient, fiam, fias, fiat, fiamus, fiatis, fiant, 
fierem, fieres, fieret, fieremus, fieretis, fierent, edo, es, edis, est, edit, 
edimus, estis, editis, edunt, edebam, edebas, edebat, edebamus, edebatis, 
edebant, edam, edes, edet, edemus, edetis, edent, edi, edisti, edit, edimus, 
edistis, ederunt, ederam, ederas, ederat, ederamus, ederatis, ederant, perfect, 
edero, ederis, ederit, ederimus, ederitis, ederint, edo, es, edis, est, edit, 
edimus, estis, editis, edunt, edebam, edebas, edebat, edebamus, edebatis, 
edebant, edam, edes, edet, edemus, edetis, edent, edi, edisti, edit, edimus, 
edistis, ederunt, ederam, ederas, ederat, ederamus, ederatis, ederant, perfect, 
edero, ederis, ederit, ederimus, ederitis, ederint, edam, edas, edat, edamus, 
edatis, edant, essem, ederem, esses, ederes, esset, ederet, essemus, 
ederemus, essetis, ederetis, essent, ederent, ederim, ederis, ederit, ederimus, 
ederitis, ederint, edissem, edisses, edisset, edissemus, edissetis, edissen, 
edor, ederis, estur, editur, edimur, edimini, eduntur, edebar, edebaris, 
edebatur, edebamur, edebamini, edebantur, edar, ederis, edetur, edemur, 
edemini, edentur, edar, edaris, edatur, edamur, edamini, edantur, ederer, 
edereris, essetur, ederetur, ederemur, ederemini, ederentur, do, das, dat, 
damus, datis, dant, dabam, dabas, dabat, dabamus, dabatis, dabant, dabo, dabis, 
dabit, dabimus, dabitis, dabunt, dedi, dedisti, dedit, dedimus, dedistis, 
dederunt, dederam, dederas, dederat, dederamus, dederatis, dederant, perfect, 
dedero, dederis, dederit, dederimus, dederitis, dederint, dem, des, det, demus, 
detis, dent, darem, dares, daret, daremus, daretis, darent, dederim, dederis, 
dederit, dederimus, dederitis, dederint, dedissem, dedisses, dedisset, 
dedissemus, dedissetis, dedissen, da, date, dato, dato, datote, danto, dor, 
daris, datur, damur, damini, dantur, dabar, dabaris, dabatur, dabamur, 
dabamini, dabantur, dabor, daberis, dabitur, dabimur, dabimini, dabuntur, 
deris, detur, demur, demini, dentur, darer, dareris, daretur, daremur, 
daremini, darentur, dare, damini, dabator, dabator, dabantor]
