noun_data = [
        ('D1', 'a'),
        ('D1', 'ae'),
        ('D1', 'am'),
        ('D1', 'a'),
        ('D1', 'ae'),
        ('D1', 'arum'),
        ('D1', 'ae'),
        ('D1', 'is'),
        ('D1', 'as'),
        ('D1', 'is'),
        ('D2', 'us'),
        # Second delension words can sometimes have irregular
        # have irregular nominative forms.
        # ('D2', ''),
        ('D2', 'i'),
        ('D2', 'o'),
        ('D2', 'um'),
        ('D2', 'o'),
        ('D2', 'i'),
        ('D2', 'orum'),
        ('D2', 'is'),
        ('D2', 'os'),
        ('D2', 'is'),
        # Third declension nominative signulars are always irregular
        # ('third_nom_sg', ''),
        ('D3', 'is'),
        ('D3', 'i'),
        ('D3', 'em'),
        ('D3', 'e'),
        ('D3', 'es'),
        ('D3', 'um'),
        ('D3', 'ibus'),
        ('D3', 'es'),
        ('D3', 'ibus'),
        ('D4', 'us'),
        ('D4', 'us'),
        ('D4', 'ui'),
        ('D4', 'um'),
        ('D4', 'u'),
        ('D4', 'us'),
        ('D4', 'uum'),
        ('D4', 'ibus'),
        ('D4', 'us'),
        ('D4', 'ibus'),
        ('D5', 'es'),
        ('D5', 'ei'),
        ('D5', 'ei'),
        ('D5', 'em'),
        ('D5', 'e'),
        ('D5', 'es'),
        ('D5', 'erum'),
        ('D5', 'ebus'),
        ('D5', 'es'),
        ('D5', 'ebus')]
